export const COURSES_RECEIVE = 'COURSES_RECEIVE';
export const COURSES_REQUEST = 'COURSES_REQUEST';
export const COURSES_REQUEST_SUCCESS = 'COURSES_REQUEST_SUCCESS';
export const COURSES_REQUEST_FAILURE = 'COURSES_REQUEST_FAILURE';